---
title: "Education and Professional Experience"
output: 
  html_document:
    toc: true
    toc_float: true

---

## Education
Columbia University Mailman School of Public Health &nbsp; &nbsp; &nbsp;&nbsp; &nbsp;           08/2020-Present  
Program: Biostatistics, Pharmaceutical Statistics track/MS  

University of Wisconsin-Madison&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  &nbsp; &nbsp; &nbsp;            01/2017-05/2020  
Major: Biochemistry in College of Agriculture & Life Science.  
Certificate：Education and Educational Services.

## Research Experience
Prof. Merrin’s Lab in University of Wisconsin-Madison &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;03/2019-05/2020  
&nbsp; &nbsp; &nbsp;&nbsp; &nbsp;Studying the roles and mechanisms of cell cycle regulators in metabolism and insulin secretion.  
&nbsp; &nbsp; &nbsp;&nbsp; &nbsp;Taking in charge of designing algorithm for signal identification and analyzed research data with
MATLAB.  

[Resume](file:///Users/yiming/Desktop/resume/cv_yiming.html)